name = "victorsibanda-dev"
compatibility_date = "2026-04-17"
workers_dev = true
preview_urls = true
main = "worker.js"

[[routes]]
pattern = "victorsibanda.dev"
custom_domain = true

[assets]
directory = "."
binding = "ASSETS"
